/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
#include "base.hpp"
#include "dev_info_manage.h"
#include "stars_base.hpp"
#include "stars_base_cond_isa_define.hpp"
#include "task_base.hpp"

namespace cce {
namespace runtime {
static constexpr rtSocInfo_t SOC_910B_INFO[] = {
    {CHIP_910_B_93, "Ascend910B1"},
    {CHIP_910_B_93, "Ascend910B2"},
    {CHIP_910_B_93, "Ascend910B3"},
    {CHIP_910_B_93, "Ascend910B4"},  // hardversion 910_93 same as 910B4
    {CHIP_910_B_93, "Ascend910B2C"},
    {CHIP_910_B_93, "Ascend910B4-1"},
    {CHIP_910_B_93, "Ascend910_9362"},
    {CHIP_910_B_93, "Ascend910_9372"},
    {CHIP_910_B_93, "Ascend910_9381"},
    {CHIP_910_B_93, "Ascend910_9382"},
    {CHIP_910_B_93, "Ascend910_9391"},
    {CHIP_910_B_93, "Ascend910_9392"},
};

BATCH_REGISTER_SOC_INFO(SOC_910B_INFO, (sizeof(SOC_910B_INFO) / sizeof(rtSocInfo_t)));

constexpr rtSocInfo_t DEV_INFO_910_93[] = {
    {CHIP_910_B_93, "Ascend910_9362"},
    {CHIP_910_B_93, "Ascend910_9372"},
    {CHIP_910_B_93, "Ascend910_9381"},
    {CHIP_910_B_93, "Ascend910_9382"},
    {CHIP_910_B_93, "Ascend910_9391"},
    {CHIP_910_B_93, "Ascend910_9392"},
};

BATCH_REGISTER_DEV_INFO(DEV_INFO_910_93, sizeof(DEV_INFO_910_93) / sizeof(rtSocInfo_t));

REGISTER_PLATFORM_LIB_INFO(CHIP_910_B_93, "libruntime_v100.so");

static const std::unordered_set<RtOptionalFeatureType> CHIP_CLOUD_V2_FEATURE{
    RtOptionalFeatureType::RT_FEATURE_OVERFLOW_MODE,
    RtOptionalFeatureType::RT_FEATURE_MODEL_ACL_GRAPH,
    RtOptionalFeatureType::RT_FEATURE_TASK_VALUE_WAIT,
    RtOptionalFeatureType::RT_FEATURE_DFX_PROCESS_SNAPSHOT,
    RtOptionalFeatureType::RT_FEATURE_IPC_MEMORY,
    RtOptionalFeatureType::RT_FEATURE_IPC_NOTIFY,
    RtOptionalFeatureType::RT_FEATURE_KERNEL_INTER_CORE_SYNC_ADDR,
    RtOptionalFeatureType::RT_FEATURE_DEVICE_DCACHE_LOCK,
    RtOptionalFeatureType::RT_FEATURE_TASK_RAND_GENERATOR,
    RtOptionalFeatureType::RT_FEATURE_KERNEL_REGISTER_V2,
    RtOptionalFeatureType::RT_FEATURE_KERNEL_TILING_KEY_SINK,
    RtOptionalFeatureType::RT_FEATURE_TASK_MEMORY_BATCH_COPY,
    RtOptionalFeatureType::RT_FEATURE_STREAM_GET_AVILIABLE_NUM,
    RtOptionalFeatureType::RT_FEATURE_TASK_CMO,
    RtOptionalFeatureType::RT_FEATURE_DRIVER_NUMA_TS_MEM_CTRL,
    RtOptionalFeatureType::RT_FEATURE_PROFILING_ONLINE,
    RtOptionalFeatureType::RT_FEATURE_TASK_FLIP,
    RtOptionalFeatureType::RT_FEATURE_DFX_ARGS_DOT_ALLOC_ERROR_LOG,
    RtOptionalFeatureType::RT_FEATURE_TASK_DVPP,
    RtOptionalFeatureType::RT_FEATURE_TASK_RDMA,
    RtOptionalFeatureType::RT_FEATURE_STREAM_DVPP_GROUP,
    RtOptionalFeatureType::RT_FEATURE_KERNEL_REGISTER_CALLBACK,
    RtOptionalFeatureType::RT_FEATURE_KERNEL_TILING_TABLE_PHY_CONTIGUOUS,
    RtOptionalFeatureType::RT_FEATURE_STREAM_RECLAIM_ASYNC,
    RtOptionalFeatureType::RT_FEATURE_MEM_HOST_REGISTER_PCIE_THROUGH,
    RtOptionalFeatureType::RT_FEATURE_TASK_TRY_RECYCLE_DISABLE_HWTS,
    RtOptionalFeatureType::RT_FEATURE_KERNEL_ELF_INCLUDE_STACK_SIZE,
    RtOptionalFeatureType::RT_FEATURE_NOTIFY_WAIT_TIMEOUT,
    RtOptionalFeatureType::RT_FEATURE_DFX_FAST_RECOVER,
    RtOptionalFeatureType::RT_FEATURE_DFX_TS_RING_BUFFER,
    RtOptionalFeatureType::RT_FEATURE_MEM_1G_HUGE_PAGE,
    RtOptionalFeatureType::RT_FEATURE_DEVICE_VISIBLE,
    RtOptionalFeatureType::RT_FEATURE_TASK_MODEL_EXECUTE_COPY_ONCE,
    RtOptionalFeatureType::RT_FEATURE_MEM_L2_CACHE_PERSISTANT,
    RtOptionalFeatureType::RT_FEATURE_DEVICE_NON_UNIFIED_ADDR,
    RtOptionalFeatureType::RT_FEATURE_DEVICE_HAS_TS_DEAMON,
    RtOptionalFeatureType::RT_FEATURE_DEVICE_GET_STARS_VERSION,
    RtOptionalFeatureType::RT_FEATURE_DEVICE_P2P,
    RtOptionalFeatureType::RT_FEATURE_PROFILING_AICPU,
    RtOptionalFeatureType::RT_FEATURE_TASK_RECYCLE_THREAD,
    RtOptionalFeatureType::RT_FEATURE_TASK_MODEL_EXECUTE_SPLIT_FUNC_CALL,
    RtOptionalFeatureType::RT_FEATURE_DRIVER_EVENT_MC2,
    RtOptionalFeatureType::RT_FEATURE_DFX_WATCH_DOG,
    RtOptionalFeatureType::RT_FEATURE_DEVICE_FAILURE_MODE_SET,
    RtOptionalFeatureType::RT_FEATURE_DFX_TS_GET_DEVICE_MSG,
    RtOptionalFeatureType::RT_FEATURE_DFX_REPORT_RAS,
    RtOptionalFeatureType::RT_FEATURE_DEVICE_MULTI_CHIP,
    RtOptionalFeatureType::RT_FEATURE_DRIVER_GET_FAULT_EVENT,
    RtOptionalFeatureType::RT_FEATURE_DEVICE_DCACHE_LOCK_DOT_ALLOC_STACK,
    RtOptionalFeatureType::RT_FEATURE_DEVICE_16K_STACK,
    RtOptionalFeatureType::RT_FEATURE_DEVICE_MESSAGE_QUEUE,
    RtOptionalFeatureType::RT_FEATURE_DFX_FAST_RECOVER_MTE_ERROR,
    RtOptionalFeatureType::RT_FEATURE_MODEL_ACL_GRAPH_SOFTWARE_ENABLE,
    RtOptionalFeatureType::RT_FEATURE_MEM_MBUF_COPY,
    RtOptionalFeatureType::RT_FEATURE_TASK_FFTS_PLUS,
    RtOptionalFeatureType::RT_FEATURE_STREAM_HUGE_DEPTH,
    RtOptionalFeatureType::RT_FEATURE_STREAM_ABORT,
    RtOptionalFeatureType::RT_FEATURE_UPDATE_SQE_TILING_KEY,
    RtOptionalFeatureType::RT_FEATURE_KERNEL_TASK_RATION,
    RtOptionalFeatureType::RT_FEATURE_TASK_MEMCOPY_RECLAIM_ASYNC_WITHOUR_PCIE_BAR,
    RtOptionalFeatureType::RT_FEATURE_STREAM_DELETE_FORCE,
    RtOptionalFeatureType::RT_FEATURE_KERNEL_ELF_NO_FUNC_TYPE,
    RtOptionalFeatureType::RT_FEATURE_DEVICE_SPM_POOL,
    RtOptionalFeatureType::RT_FEATURE_MODEL_UPDATE_SQE_TILING_KEY,
    RtOptionalFeatureType::RT_FEATURE_DFX_FAST_RECOVER_DOT_RESOURCE_CLEAN,
    RtOptionalFeatureType::RT_FEATURE_TASK_EXEC_TIMEOUT_SCALE_MODIFY,
    RtOptionalFeatureType::RT_FEATURE_MODEL_ABORT,
    RtOptionalFeatureType::RT_FEATURE_MODEL_ABORT_USE_DEFAULT_STREAM,
    RtOptionalFeatureType::RT_FEATURE_KERNEL_MEMORY_POOL,
    RtOptionalFeatureType::RT_FEATURE_MEM_HOST_REGISTER,
    RtOptionalFeatureType::RT_FEATURE_STREAM_EXTENSION,
    RtOptionalFeatureType::RT_FEATURE_KERNEL_META_TYPE_SU_STACK_SIZE,
    RtOptionalFeatureType::RT_FEATURE_DFX_FLOAT_OVERFLOW_DEBUG,
    RtOptionalFeatureType::RT_FEATURE_DEVICE_GET_RESOURCE_NUM_DYNAMIC,
    RtOptionalFeatureType::RT_FEATURE_DEVICE_SET_RUNTIME_CAPABLITY,
    RtOptionalFeatureType::RT_FEATURE_STREAM_DOT_SET_MODE,
    RtOptionalFeatureType::RT_FEATURE_TASK_MEMORY_COPY_DOT_HOST,
    RtOptionalFeatureType::RT_FEATURE_IPC_EVENT,
    RtOptionalFeatureType::RT_FEATURE_KERNEL_ELF_16K_STACK,
    RtOptionalFeatureType::RT_FEATURE_MODEL_STREAM_LOAD_COMPLETE_TO_RTSQ,
    RtOptionalFeatureType::RT_FEATURE_MODEL_EXE_DOT_NEED_LOAD_COMPLETE,
    RtOptionalFeatureType::RT_FEATURE_TASK_MEMCPY_D2D_BY_OFFSET,
    RtOptionalFeatureType::RT_FEATURE_DEVICE_TS_DEAMON_OPEN_EX,
    RtOptionalFeatureType::RT_FEATURE_TASK_DSA_UPDATE,
    RtOptionalFeatureType::RT_FEATURE_STREAM_ATTR_FAILURE_MODE,
    RtOptionalFeatureType::RT_FEATURE_STREAM_ATTR_OVERFLOW_CHECK,
    RtOptionalFeatureType::RT_FEATURE_STREAM_ATTR_USER_CUSTOM_TAG,
    RtOptionalFeatureType::RT_FEATURE_STREAM_TAG,
    RtOptionalFeatureType::RT_FEATURE_KERNEL_ADDR_PREFETCH_CNT,
    RtOptionalFeatureType::RT_FEATURE_DEVICE_C2C_SYNC,
    RtOptionalFeatureType::RT_FEATURE_KERNEL_BINARY_LOAD_DOT_WITHOUT_TILING,
    RtOptionalFeatureType::RT_FEATURE_KERNEL_BINARY_GET_FUNCTION_DOT_BY_NAME,
    RtOptionalFeatureType::RT_FEATURE_DRIVER_ESCHED_QUERY_INFO,
    RtOptionalFeatureType::RT_FEATURE_MODEL_ID_FOR_AICPU,
    RtOptionalFeatureType::RT_FEATURE_NOTIFY_WAIT,
    RtOptionalFeatureType::RT_FEATURE_KERNEL_UMA_SUPER_ARGS_ALLOC,
    RtOptionalFeatureType::RT_FEATURE_NOTIFY_RESET,
    RtOptionalFeatureType::RT_FEATURE_TASK_CMO_DOT_NO_LOG,
    RtOptionalFeatureType::RT_FEATURE_KERNEL_NAME_MAP_TABLE,
    RtOptionalFeatureType::RT_FEATURE_MEM_POOL_ALIGN,
    RtOptionalFeatureType::RT_FEATURE_DEVICE_FLOAT_STATUS,
    RtOptionalFeatureType::RT_FEATURE_DEVICE_EVENT_POOL,
    RtOptionalFeatureType::RT_FEATURE_DEVICE_CTRL_SQ,
    RtOptionalFeatureType::RT_FEATURE_MEM_WAIT_PROF,
    RtOptionalFeatureType::RT_FEATURE_DFX_ERR_GET_AND_REPAIR,
};

REGISTER_CHIP_FEATURE_SET(CHIP_910_B_93, CHIP_CLOUD_V2_FEATURE);

static constexpr uint32_t ASYNC_TASK_D2D_QOS = 6U;
constexpr uint32_t TS_FEATURE_MC2_RTS_SUPPORT_HCCL_PROP = 23;
static constexpr uint32_t RT_STARS_MAX_KERNEL_CREDIT_UINT32 = 254U; // STARS MAX KERNEL_CREDIT = 255.
static constexpr uint32_t RT_STARS_DEFAULT_KERNEL_CREDIT_UINT32 = 254U; // The STARS reference time is 1090921693.184 us.
static constexpr float64_t RT_STARS_TASK_KERNEL_CREDIT_SCALE_MIN = 0.001F;  // 0.001(us) = 1ns

static constexpr uint32_t RT_STARS_ATOMIC_DMA_CAPS = RT_ATOMIC_CAPABILITY_SIGNED | RT_ATOMIC_CAPABILITY_SCALAR8 |
                                                     RT_ATOMIC_CAPABILITY_SCALAR16 | RT_ATOMIC_CAPABILITY_SCALAR32;

static constexpr std::array<uint32_t, RT_ATOMIC_OPERATION_MAX_VAL> GetStarsP2PAtomicCaps()
{
    std::array<uint32_t, RT_ATOMIC_OPERATION_MAX_VAL> caps{};
    caps[RT_ATOMIC_OPERATION_DMA_ADD] = RT_STARS_ATOMIC_DMA_CAPS;
    caps[RT_ATOMIC_OPERATION_DMA_MIN] = RT_STARS_ATOMIC_DMA_CAPS;
    caps[RT_ATOMIC_OPERATION_DMA_MAX] = RT_STARS_ATOMIC_DMA_CAPS;
    return caps;
}

static const DevProperties CHIP_CLOUD_V2_PROPERTIES = {
    .engineType = "STARS",
    .isStars = true,
    .isStarsV2 = false,
    .pthreadStackSize = 0U,
    .eventWaitTimeout = EventWaitTimeoutType::SET_OP_WAIT_TIMEOUT_CONFIG,
    .tsCount = 1U,
    .defaultTaskRatio = NORMAL_TASK_RATION,
    .sqTailOffset = STARS_SIMPLE_SQ_TAIL_OFFSET,
    .maxGroupId = MAX_GROUP_ID,
    .reduceOverflow = ReduceOverflowType::REDUCE_NO_OVERFLOW,
    .supportOverflowMode = OVERFLOW_MODE_SATURATION | OVERFLOW_MODE_INFNAN,
    .sdmaReduceKind = 0x7C00U,
    .starsResourceAddrCalculateMethod = StarsResourceAddrCalculateMethod::STARS_RESOURCE_ADDR_CALCULATE_BY_DEVICE_INFO,
    .eventBase = RT_STARS_BASE_ADDR + STARS_EVENT_BASE_ADDR,
    .starsBaseMethod = StarsBaseMethod::STARS_BASE_CALCULATE_STATIC,
    .fsmSelBase = RT_STARS_BASE_ADDR + STARS_SIMPLE_RTSQ_FSM_SEL_REG,
    .notifyBase = RT_STARS_BASE_ADDR + STARS_NOTIFY_BASE_ADDR,
    .starsNotifyTableSize = STARS_NOTIFY_NUM_OF_SINGLE_TABLE,
    .ipcNotifyNumMask = 0x1FFUL,
    .mc2FeatureFlag = TS_FEATURE_MC2_RTS_SUPPORT_HCCL_PROP,
    .stackPhyBase = RT_SCALAR_BUFFER_SIZE_32K_75,
    .maxCustomerStackSize = DEFAULT_CUSTOM_STACK_SIZE_MAX,
    .aicNum = RT_AICORE_NUM_25,
    .aivNum = RT_AIVECTOR_NUM_50,
    .ringbufSize = DEVICE_RINGBUFFER_SIZE,
    .hugeManagedFlag = SVM_HOST_AGENT,
    .memAllocPctraceFlag = MEM_SVM_HUGE,
    .memInfoType = RT_MEM_INFO_TYPE_HBM_SIZE,
    .taskPrefetchCount = PREFETCH_CNT_8,
    .maxAllocHugeStreamNum = DEFAULT,
    .reduceAicNum = true,
    .timeoutUpdateMethod = TimeoutUpdateMethod::DEFAULT_METHOD,
    .hugePolicyFlag = DEFAULT,
    .memInfoMapType = DEFAULT,
    .resAllocRange = DEFAULT,
    .supportSnapshot = SupportSnapshot::SUPPORT,
    .MaxKernelCredit = RT_STARS_MAX_KERNEL_CREDIT_UINT32,
    .eventTimestampFreq = RT_CHIP_CLOUD_V2_TIMESTAMP_FREQ,
    .taskEngineType = EngineCreateType::STARS_ENGINE,
    .CmoSqeVersion = SqeVersion::CMO_SQE_VERSION_V2,
    .DefaultKernelCredit = RT_STARS_DEFAULT_KERNEL_CREDIT_UINT32,
    .starsDefaultKernelCredit = RT_STARS_DEFAULT_KERNEL_CREDIT,
    .KernelCreditScale = RT_STARS_TASK_KERNEL_CREDIT_SCALE_MIN,
    .isSupportInitFuncCallPara = true,
    .rtsqVirtualAddr = {RT_STARS_BASE_ADDR + STARS_SIMPLE_RTSQ_FSM_SEL_REG,
        STARS_SIMPLE_SQ_ENABLE_OFFSET,
        STARS_SIMPLE_SQ_TAIL_OFFSET,
        STARS_SIMPLE_SQ_HEAD_OFFSET},
    .rtsqFsmStateAddrCalMethod = RtsqFsmStateAddrCalMethod::FSM_ADDR_CALCULATE_BY_DEVICE_INFO,
    .starsBaseAddrMethod = StarsBaseAddrMethod::STARS_BASE_CALCULATE_STATIC,
    .rtSqEnableAddrCalMethod = RtSqEnableAddrCalMethod::RT_SQ_ENABLE_ADDR_CAL_STATIC,
    .isSupportDvppAccelerator = true,
    .isSupportDevVA2PA = false,
    .cmoAddrInfoType = CmoAddrInfoType::CMO_ADDR_INFO_TYPE_DAFAULT,
    .memcpyAsyncTaskD2DQos = ASYNC_TASK_D2D_QOS,
    .isMemcpyAsyncTaskSqeType = true,
    .sqeDepth = UINT32_MAX,
    .cqeSize = RT_VIRTUAL_CQE_SIZE,
    .cqeDepth = static_cast<uint32_t>(CqeDepth::CQE_DEPTH_DVPP_GRP),
    .cqeWaitTimeout = RT_REPORT_STARS_TIMEOUT_TIME,
    .getRtsqPosition = UINT16_MAX,
    .creditStartValue = UINT16_MAX,
    .argsItemSize = MULTI_GRAPH_ARG_ENTRY_SIZE_OTH,
    .argInitCountSize = DEFAULT_INIT_CNT_OTH,
    .argsAllocatorSize = TINY_INIT_CNT_DEFAULT,
    .superArgAllocatorSize = SUPER_ARG_AllOC_SIZE_128,
    .maxArgAllocatorSize = ARG_MAX_ENTRY_INIT_NUM,
    .handleAllocatorSize = HANDLE_ALLOCATOR_SIZE_1024,
    .kernelInfoAllocatorSize = KERNEL_INFO_ALLOC_SIZE,
    .isNeedlogErrorLevel = true,
    .overflowMode = true,
    .opExecuteTimeout = false,
    .omArchVersion = OMArchVersion::omArchVersion_4,
    .checkArchVersionCompatibility = CheckArchVersionCompatibility::Arch_Version_Compat_V220,
    .dcacheLockMixType = DcacheLockMixType::DCACHE_LOCK_MIX_TYPE_FROM_910_B_93,
    .kernelFuncType = KernelFuncType::Kernel_FUC_TYPE_SUPP_AICORE,
    .taskPoolSizeFromRtsqDepth = true,
    .taskPoolSize = 0U,
    .getTsMemTypeMethod = GetTsMemTypeMethod::GET_TS_MEM_TYPE_STATIC,
    .enabledTSNum = ENABLED_TS_NUM_1,
    .deviceSatStatus = DeviceSatStatus::DEVICE_SAT_STATUS_V2,
    .ringBufferMemCopyCycleTimes = 1U,
    .tsOverflowHandling = TsOverflowHandling::TS_OVER_FLOW_HANDING_INVALID,
    .getCapabilityMethod = GetCapabilityMethod::GET_CAPABILITY_BY_DRIVER_CHECK,
    .memcpyDescriptorSize = MEMCPY_DESC_SIZE_V1,
    .cmoDDRStructInfoSize = sizeof(rtCmoAddrInfo),
    .streamWaitEventTimeout = StreamWaitEventTimeout::CUSTOM,
    .timelineEventId = TIMELINE_EVENT_ID_DEFAULT,
    .deviceSatStatusImpl = DeviceSatStatusImpl::DEVICE_SAT_STATUS_STREAM_LEVEL,
    .allocManagedFlag = AllocManagedFlag::ALLOC_MANAGED_MEM_HOST_AGENT,
    .sdmaCopyMethod = SdmaCopyMethod::SDMA_COPY_BY_HAL_WITH_OFFLINE,
    .eventPoolSize = 64U,
    .rtsqShamt = 0x7FFU,
    .supportCreateTaskRes = SupportCreateTaskRes::CREATE_TASK_RES_SUPPORT,
    .physicalMemTypePolicy = PhysicalMemTypePolicy::DEFAULT,
    .aicNumForCoreStack = RT_AICORE_NUM_25,
    .engineWaitCompletionTImeout = 0UL,
    .reportWaitTimeout = RT_REPORT_TIMEOUT_TIME,
    .hostAtomicCapabilities = {},
    .p2pAtomicCapabilities = GetStarsP2PAtomicCaps(),
    .maxPersistTaskNum = 60000U,
    .maxSupportTaskNum = 67108864U,
    .stubEventCount = 65536U,
    .maxReportTimeoutCnt = 360,
    .rtcqDepth = 0U,
    .baseAicpuStreamId = 2048U,
    .expandStreamRsvTaskNum = 0U,
    .expandStreamSqDepthAdapt = 0U,
    .expandStreamAdditionalSqeNum = 1U,
    .rsvAicpuStreamNum = 1024U,
    .maxPhysicalStreamNum = 2038U,
    .maxAllocStreamNum = 32768U,
    .rtsqDepth = 2048U,
    .maxTaskNumPerStream = 2013U,
    .maxTaskNumPerHugeStream = 0U,
    .rtsqReservedTaskNum = 35U,

    .simtWarpSize = 0U,
    .simtMaxThreadPerVectorCore = 0U,
    .simtUbufPerVectorCore = 0U,
    .simtMaxGridDimX = 0U,
    .simtMaxGridDimY = 0U,
    .simtMaxGridDimZ = 0U,
    .simtMaxBlockPerGrid = 0U,
    .simtMaxThreadsPerBlock = 0U,
    .simtMaxBlockDimX = 0U,
    .simtMaxBlockDimY = 0U,
    .simtMaxBlockDimZ = 0U,
    .cvArchType = DeviceCvArchType::CV_ARCH_SEPARATION,
    .npuArch = 0,
    .sqDisableStatPollingCycleNum = SQ_DISABLE_POLLING_CYCLE_COMMON_CNT,
};

REGISTER_DEV_PROPERTIES(CHIP_910_B_93, CHIP_CLOUD_V2_PROPERTIES);
}
}
