# [Platform Info configuration begin]
#**************************************************************************************
#
[version]
SoC_version=KirinX90
Short_SoC_version=KirinX90
AIC_version=AIC-L-300
CCEC_AIC_version=dav-l300
Compiler_aicpu_support_os=false
NpuArch=3003
Chip_type=200

[SoCInfo]
ai_core_cnt=1
vector_core_cnt=1
ai_cpu_cnt=
memory_type=0
memory_size=
l2_type=0
l2_size=0
l2PageNum=0
normal_stream_num=192
normal_stream_depth=1024
huge_stream_num=0
huge_stream_depth=0
core_type_list=AICore,VectorCore
cube_vector_mix=cube_vector_mix
vir_type_list=1

[AICoreSpec]
cube_m_size=16
cube_n_size=8
cube_k_size=16
vec_calc_size=128
l0_a_size=65536
l0_b_size=65536
l0_c_size=131072
l1_size=1048576
fb0_size=2048
fb1_size=1024
fb2_size=1024
fb3_size=2048
bt_size=1024
ub_size=131072
ubblock_size=32
load3d_constraints=1
support_fixpipe=1
sparsity=1
padding_size=32

[AICoreMemoryRates]

[DtypeMKN]
Default=16,16,8
DT_INT8=16,32,16
DT_UINT8=16,32,16
DT_INT4=16,64,16
DT_INT2=
DT_UINT2=
DT_UINT1=

[CPUCache]
AICPUSyncBySW=0
TSCPUSyncBySW=0

[AICoreintrinsicDtypeMap]

[SoftwareSpec]
jit_compile_default_value=1