name: runtime_action

on:
  workflow_dispatch:
    inputs:
      repo_name:
        type: string
        default: 'runtime'
      target_branch:
        type: string
        default: 'master'
      pr_number:
        type: string
        default: '3'



